### ISSUE TITLE
Create CI to test Tekton task against lifecycle (master)

### ISSUE THREAD

**Issue by zmackie** [buildpacks/tekton-integration#1]
@jromero Feel free to fill this out a bit more.

**Comment by dfreilich** [comment]
@jromero We had mentioned this in a previous discussion. Do we want to add it to our project backlog?

**Comment by jromero** [comment]
Closing this as it should be the responsibility of the lifecycle IMO. This repo while in development should test only against released versions. We wouldn't want any failing builds due to **ongoing** work in the lifecycle. That said, the assets in this repo could be used by the lifecycle to automate it's testing against Tekton.
